### ISSUE TITLE
Inform user about what next steps to take based on test result

### ISSUE THREAD

**Issue by nhternup** [foundation-for-environmental-monitoring/ffem-app#12]
At the completion of the test, provide the user with risk information and about available options to mitigate any risk

The result could be compared with the standard values provide by WHO as below:

## WHO and Indian standards of drinking water.
No. | Water quality parameter | Indian Standards<br/>(mg/l except pH) | WHO standards<br/>(mg/l except pH)
-- | -- | -- | --
1 | pH | 6.5-8.5 | 6.5-8.5
2 | Fluoride | 1 | 1.5
3 | Iron | 0.3 | Not available
4 | Nitrate | 45 | 50
5 | Arsenic | 0.05 | 0.01
6 | Phosphate | 0.3 | Not available
7 | Sulphate | 200 | 500
8 | Residual chlorine | 0.2 | 0.2
9 | Copper | 1.5 | 2
10 | Chloride | 250 | 250
11 | Chromium(VI) | Not available | 0.05
12 | Aluminium | 0.2 | 0.2

**Comment by saurabhlevin** [comment]
@PradeepBalkunde - could you share units too? The standards for Aluminum and Copper seem to be very different

**Comment by Pradeepbal1** [comment]
@saurabh - For aluminium & Copper 0.2 & 1.5 mg/L respectively ( Indian standards)
