### ISSUE TITLE
ffem water crashing

### ISSUE THREAD

**Issue by saurabhlevin** [foundation-for-environmental-monitoring/ffem-app#13]
#### Problem description
Crashes during calibration and testing. 

#### Versions 

   * **App name and version:**  ffem Water, Beta 1.1
   * **Device:** Various
   * **OS version:** Various

#### Steps to reproduce the problem

    1. Run a calibration or test when not in user mode

#### Expected behavior
Should complete test without crashing

#### How often does it happen
Always 

#### Other information *[Things you tried, related issues, suggestions on how to fix it...]*
Only happens when not in user mode

**Comment by nhternup** [comment]
As this does not affect user mode. An immediate fix is not required. Will be fixed in the next version.
