### ISSUE TITLE
Add Arsenic strip test feature

### ISSUE THREAD

**Issue by saurabhlevin** [foundation-for-environmental-monitoring/ffem-app#16]
#### Problem description
Our arsenic test kit is not ready yet due to iron interference, so some customers will need to use the hach test strips instead. 
The ffem water app needs the option to launch an arsenic strip test with the akvo strip test card. There should also be uuid associated so the test can be launched from collect

#### Versions

   * **App name and version:** FFEM Water
   * **Device:** 
   * **OS version:** 
  
#### Steps to reproduce the problem

    1. 
    2. 
    3.

**Comment by nhternup** [comment]
Added in beta 1.1 version
