### ISSUE TITLE
Multiple Reference Calibrations

### ISSUE THREAD

**Issue by ishangupta42** [foundation-for-environmental-monitoring/ffem-app#20]
For FFEM Experiment

Attempting to improve the Automatic (one step) calibration accuracy using multiple reference calibrations as opposed to just one (current version).

User flow of events:
1) User takes distilled water sample and adds reagent for the parameter
2) RGB values for the 0 standard so recorded are compared against the 0 standard RGB values of all pre-existing reference calibrations values
3) The reference calibration whose 0 standard distance (D) value is least is then selected as the reference calibration on which offset adjustments are made. App should communicate to the user (tester) the name associated with this pre-existing reference calibration and also the D value determined.
4) If the D value is sufficiently large (threshold TBD) the tester will do a full new calibration and add it to the set of pre-existing reference calibrations (suggesting that the device being used produces a sufficiently unique colour set for the same standards+reagents)

Pre-existing Reference Calibrations:
Set of RGB values for each calibration standard point and an associated identifying name for the same for manual correlations.
Editable asset in which these values are stored/referenced so that new calibrations can be added/referenced on dynamically (ie. not hardcoded and changeable without updating the app)

**Comment by nhternup** [comment]
**Implemented in:**
Experiment v241

**New json property:**
'references' added under 'results'
https://github.com/foundation-for-environmental-monitoring/ffem-app/blob/236af896e3db9303d3cbcfc632647db8fe8d4369/caddisfly-app/app/src/experiment/assets/tests.json#L486

**Format:**
Comma separated colors in hex with reference description at the end.
