### ISSUE TITLE
One Step Calibration for Free Chlorine

### ISSUE THREAD

**Issue by ishangupta42** [foundation-for-environmental-monitoring/ffem-app#32]
#### Problem description
Need to try out one step calibration (referencing multiple calibrations) like how we have done for Fluoride. I have collected a few Free Chlorine calibration files and will upload them to a Google Spreadsheet.

Please set this up.

**Comment by nhternup** [comment]
[Experimental tests](https://github.com/foundation-for-environmental-monitoring/experimental-tests/blob/ffem-experiment/experimental_tests.json#L23) updated
