### ISSUE TITLE
Time Delay UI Options: Retry

### ISSUE THREAD

**Issue by ishangupta42** [foundation-for-environmental-monitoring/ffem-app#44]
Apps return errors (for no discernible reason) after doing a test. In order to immediately redo the test with that sample, the user has to enable diagnostic mode, go to settings, select ignore time delay and then return to the FFEM Collect and then relaunch the test. This costs the user precious time for a time-sensitive colorimetric reaction. 

It would be great if there were two retry options upon returning the error message: "retry with time delay" (redo sample preparation and start again) and "immediately retry" (to test with the same sample immediately). The fact that the user must lift up the phone to access the retry options will help give the user a chance to re-place the cuvette on top of the phone, perhaps more accurately

**Comment by nhternup** [comment]
Cancelled until further notice
