### ISSUE TITLE
Time Delay UI Options: Start Button

### ISSUE THREAD

**Issue by ishangupta42** [foundation-for-environmental-monitoring/ffem-app#45]
This may be handled by including the instructions for doing a test in the UI flow from launching a test. However, I find many people are taken by surprise when they hit next and a timer starts running immediately. Some more information for the user "have you done this this and this? okay now start the timer" and a "start timer" button would be helpful for users.

**Comment by ishangupta42** [comment]
It might be worthwhile adding a "skip timer" button as well.

**Comment by ishangupta42** [comment]
Closed this issue by mistake

**Comment by nhternup** [comment]
Cancelled until further notice
