### ISSUE TITLE
Time Delay UI Options: Visual Instructions

### ISSUE THREAD

**Issue by ishangupta42** [foundation-for-environmental-monitoring/ffem-app#46]
Needs to be more communication from the app to the user about the timer rundown ending or approaching it's conclusion, by which time the user should have kept the phone and cuvette in position. 

- Maybe the beeping could become more rapid in the last 30 seconds?

- Maybe the app (timer) can be run in background mode, and the screen lock be enabled only in the last 30 seconds of the timer rundown? That way users can continue to use their (personal) phones until such time as it is necessary. If this is possible, a suitable notification or communication needs to be conveyed to the user (maybe like a push notification?)

**Comment by nhternup** [comment]
Cancelled until further notice
