### ISSUE TITLE
Update to Arsenic test

### ISSUE THREAD

**Issue by saurabhlevin** [foundation-for-environmental-monitoring/ffem-app#48]
#### Problem description
We have a new Total Arsenic test (as opposed to only Arsenic (III)). The ranges in the app need to be changed for the next release so that we can simplify calibration.

New ranges:
0 ppm
0.05 ppm (above this is unsafe)
0.1 ppm
0.3 ppm 
0.5 ppm

The uuid and name of the test do not need to cahnge

**Comment by nhternup** [comment]
[Released in version Beta 1.3.5](https://github.com/foundation-for-environmental-monitoring/ffem-app/releases/tag/v1.0-beta.1.3.5)
