### ISSUE TITLE
Add ability to run tests directly without survey forms

### ISSUE THREAD

**Issue by nhternup** [foundation-for-environmental-monitoring/ffem-app#49]
Add a **Run Test** button to main screen

![runtest](https://user-images.githubusercontent.com/4124856/64219733-44952080-cee4-11e9-9020-c65f9f8fd839.png)

**Comment by nhternup** [comment]
Change UI layout of main screen

**Run Test button color:**
#5CA781

| **Current**  | **New** |
| ------------- | ------------- |
| ![current](https://user-images.githubusercontent.com/4124856/64357595-980d8880-d022-11e9-85a3-4139653d3e17.png) | ![new](https://user-images.githubusercontent.com/4124856/64357625-a65ba480-d022-11e9-9402-4b5b9a2ef1db.png)  |

**Comment by saurabhlevin** [comment]
This looks good but the colour is a little different from the brand colours we had chosen..
For FFEM Water, the colour of the "Run Test" Button should be 42BABB
For FFEM Soil, the colour should E17E25

**Comment by nhternup** [comment]
| | |
| ------------- | ------------- |
| ![main-water](https://user-images.githubusercontent.com/4124856/65001997-81fba400-d90f-11e9-94b2-a1a2781b45af.png) | ![main-soil](https://user-images.githubusercontent.com/4124856/65002010-8fb12980-d90f-11e9-9e74-813806c84b1e.png) |

**Comment by saurabhlevin** [comment]
Looks great!

**Comment by ishangupta42** [comment]
@nhternup please release "Run Test" feature for FFEM Water as well.

**Comment by nhternup** [comment]
Released:
https://github.com/foundation-for-environmental-monitoring/ffem-app/releases/tag/v1.0-water.1.3.8
