### ISSUE TITLE
Update json for Available Potassium

### ISSUE THREAD

**Issue by ishangupta42** [foundation-for-environmental-monitoring/ffem-app#50]
I have updated the JSON to edit the Available Potassium parameter (just as I had done previously with FFEM Water). However, there is an urgent requirement to demo and deliver a kit tomorrow.

**Changes:**

- "ranges": "0,10,20,40"
to
"ranges": "0,10,20,30"

- "grayScale": false

**Committed in:**

- https://github.com/foundation-for-environmental-monitoring/ffem-app/commit/7017d52cb3e51699b66a2c5ebc7f81898b97c15e

Please release **ffem Soil** with this update as soon as possible.

**Comment by nhternup** [comment]
App updated
