### ISSUE TITLE
Feature request: add option to run multiple simultaneous tests for coliforms

### ISSUE THREAD

**Issue by saurabhlevin** [foundation-for-environmental-monitoring/ffem-app#54]
#### Problem description
We need to be able to run multiple (at least 4) coliforms tests simultaneously on the same setup. Currently, a carousel rotates 4 test chambers so that they align over the phone camera at different times. 

Could we have a feature whereby a user could enter the number of tests (n), and every sample get assigned to a different ID? i.e, if a user is running 4 tests simultaneously, there are 4 ID's created (say - a, b, c, d). The first image taken then corresponds to sample a), the second to sample b),and so on, until the fifth image which gets assigned to sample a) again, and the cycle repeats. 

#### Versions
 
FFEM Experiment - coliforms test

**Comment by saurabhlevin** [comment]
@nhternup - I just noticed your commit above. was it meant to add the ID feature? because I can't actually see that option in the app (build 252). I only get a "number of samples" option - which seems to refer to the number of images being taken

**Comment by nhternup** [comment]
Cancelled until further notice
