### ISSUE TITLE
Flash not coming on during coliforms test

### ISSUE THREAD

**Issue by saurabhlevin** [foundation-for-environmental-monitoring/ffem-app#55]
#### Problem description
The flash doesn't seem to come on during the coliforms test, which results in un-analyzable images.
Note - I tried turning flash mode on as well, but that didn't fix the problem

#### Versions

   * **FFEM Experiment Build 251:** 
   * **Asus Zenfone C, Moto G3, Moto G5s, samsung J2**

**Comment by nhternup** [comment]
Fixed in build 252
