### ISSUE TITLE
Test results displayed are disappearing too fast and cannot be recorded in some phones

### ISSUE THREAD

**Issue by srijana-ya** [foundation-for-environmental-monitoring/ffem-app#65]
The results displayed are disappearing too fast to be recorded.
The result disappears in split second and the screen goes back to the list of parameters while running the normal tests. (Not the calibration test)

 ffem water
Beta 1.4.0

After Calibrating Fluoride
1. Go to the home screen
2. Click on 'Run test'
3. Scroll down to 'Fluoride' and select it
4. Select no dilution
5. Run the test
6. Observe there is no test result and the screen goes back to the list of parameters

**Expected behavior**
Tests Results disappearing too fast

**Smartphone:**
1. Redmi 8A Dual
 - OS: Android
 - Version: Android 9.0, MIUI 11

2.  Meizu C9
- OS: Android
- Version : Android 8.1.

Link for a screen recording attached below:
https://drive.google.com/file/d/1pcDTyZgbdLX4uRipm_QrIokmuXKANCsD/view?usp=sharing

**Comment by nhternup** [comment]
Does this occur in normal mode also or is it only in diagnostic mode?

**Comment by srijana-ya** [comment]
Only in Diagnostic Mode

**Comment by srijana-ya** [comment]
Only in Diagnostic mode and only for the phones mentioned
